#!/usr/bin/env bash
set -euo pipefail

# ─── helpers ──────────────────────────────────────────────────────────────────

log()  { echo "[ratchet] $*"; }
fail() { echo "::error::$*"; exit 1; }

set_output() {
  local key="$1" value="$2"
  echo "${key}=${value}" >> "${GITHUB_OUTPUT:-/dev/null}"
}

# ─── validate inputs ──────────────────────────────────────────────────────────

: "${RATCHET_API_KEY:?api-key input is required}"

RATCHET_CLICKS="${RATCHET_CLICKS:-7}"
RATCHET_MODE="${RATCHET_MODE:-normal}"
RATCHET_CREATE_PR="${RATCHET_CREATE_PR:-true}"

if [[ "$RATCHET_MODE" != "normal" && "$RATCHET_MODE" != "harden" ]]; then
  fail "mode must be 'normal' or 'harden', got: $RATCHET_MODE"
fi

# ─── detect provider from key prefix ─────────────────────────────────────────

if [[ "$RATCHET_API_KEY" == sk-ant-* ]]; then
  export ANTHROPIC_API_KEY="$RATCHET_API_KEY"
  log "Provider: Anthropic"
elif [[ "$RATCHET_API_KEY" == sk-or-* ]]; then
  export OPENROUTER_API_KEY="$RATCHET_API_KEY"
  log "Provider: OpenRouter"
elif [[ "$RATCHET_API_KEY" == sk-* ]]; then
  export OPENAI_API_KEY="$RATCHET_API_KEY"
  log "Provider: OpenAI"
else
  # Unknown prefix — try as OpenRouter (most permissive)
  export OPENROUTER_API_KEY="$RATCHET_API_KEY"
  log "Provider: OpenRouter (unknown key prefix)"
fi

if [[ -n "${RATCHET_LICENSE_KEY:-}" ]]; then
  export RATCHET_LICENSE="$RATCHET_LICENSE_KEY"
fi

# ─── install Node + ratchet CLI ───────────────────────────────────────────────

if ! command -v node &>/dev/null || [[ "$(node --version | cut -c2- | cut -d. -f1)" -lt 18 ]]; then
  log "Installing Node.js 18..."
  curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  apt-get install -y nodejs
fi

log "Node $(node --version) / npm $(npm --version)"

if ! command -v ratchet &>/dev/null; then
  log "Installing ratchet CLI..."
  npm install -g ratchet-run
fi

log "Ratchet $(ratchet --version 2>/dev/null || echo 'unknown')"

# ─── capture score before ─────────────────────────────────────────────────────

TARGET_ARG=""
if [[ -n "${RATCHET_TARGET:-}" ]]; then
  TARGET_ARG="--target $RATCHET_TARGET"
fi

log "Running pre-scan..."
SCAN_BEFORE_OUTPUT="$(ratchet scan $TARGET_ARG --json 2>/dev/null || echo '{}')"
SCORE_BEFORE="$(echo "$SCAN_BEFORE_OUTPUT" | node -e "
  let d=''; process.stdin.on('data',c=>d+=c).on('end',()=>{
    try { const j=JSON.parse(d); process.stdout.write(String(j.total??0)); }
    catch { process.stdout.write('0'); }
  });
" 2>/dev/null || echo "0")"

log "Score before: $SCORE_BEFORE"
set_output "score-before" "$SCORE_BEFORE"

# ─── run ratchet torque ───────────────────────────────────────────────────────

TORQUE_ARGS="--clicks $RATCHET_CLICKS --mode $RATCHET_MODE"
[[ -n "$TARGET_ARG" ]] && TORQUE_ARGS="$TORQUE_ARGS $TARGET_ARG"

log "Running: ratchet torque $TORQUE_ARGS"
TORQUE_OUTPUT="$(ratchet torque $TORQUE_ARGS 2>&1)" || true
echo "$TORQUE_OUTPUT"

# Parse clicks-landed from output
CLICKS_LANDED="$(echo "$TORQUE_OUTPUT" | grep -oP '\d+(?= click(s)? landed)' | tail -1 || echo "0")"
set_output "clicks-landed" "$CLICKS_LANDED"

# ─── capture score after ──────────────────────────────────────────────────────

log "Running post-scan..."
SCAN_AFTER_OUTPUT="$(ratchet scan $TARGET_ARG --json 2>/dev/null || echo '{}')"
SCORE_AFTER="$(echo "$SCAN_AFTER_OUTPUT" | node -e "
  let d=''; process.stdin.on('data',c=>d+=c).on('end',()=>{
    try { const j=JSON.parse(d); process.stdout.write(String(j.total??0)); }
    catch { process.stdout.write('0'); }
  });
" 2>/dev/null || echo "0")"

log "Score after: $SCORE_AFTER"
set_output "score-after" "$SCORE_AFTER"

# ─── open PR ──────────────────────────────────────────────────────────────────

set_output "pr-url" ""

if [[ "$RATCHET_CREATE_PR" == "true" ]]; then
  if ! command -v gh &>/dev/null; then
    fail "gh CLI not found. Please add 'actions/setup-gh' or use a runner image that includes gh."
  fi

  # Determine PR title
  if [[ -n "${RATCHET_PR_TITLE:-}" ]]; then
    PR_TITLE="$RATCHET_PR_TITLE"
  else
    DETECTED_TARGET="${RATCHET_TARGET:-$(basename "$GITHUB_WORKSPACE")}"
    PR_TITLE="Ratchet: ${DETECTED_TARGET} improvements"
  fi

  # Build PR body from ratchet report
  REPORT_BODY="## Ratchet Report

**Score:** ${SCORE_BEFORE} → ${SCORE_AFTER} (+$((SCORE_AFTER - SCORE_BEFORE)))
**Clicks landed:** ${CLICKS_LANDED} / ${RATCHET_CLICKS}
**Mode:** ${RATCHET_MODE}

<details>
<summary>Torque output</summary>

\`\`\`
${TORQUE_OUTPUT}
\`\`\`

</details>

---
*Generated by [Ratchet](https://github.com/kcemate/ratchet)*"

  # Create a branch for the PR
  BRANCH_NAME="ratchet/improvements-$(date +%Y%m%d-%H%M%S)"
  git config --global user.email "ratchet-bot@users.noreply.github.com"
  git config --global user.name "Ratchet Bot"
  git checkout -b "$BRANCH_NAME"
  git add -A
  git diff --cached --quiet || git commit -m "$PR_TITLE"
  git push origin "$BRANCH_NAME"

  PR_URL="$(gh pr create \
    --title "$PR_TITLE" \
    --body "$REPORT_BODY" \
    --base "${GITHUB_BASE_REF:-main}" \
    --head "$BRANCH_NAME" 2>&1 | grep 'https://' | tail -1 || echo "")"

  log "PR created: $PR_URL"
  set_output "pr-url" "$PR_URL"
fi

log "Done."
