import { Command } from 'commander';
import chalk from 'chalk';
import { readFile, readdir } from 'fs/promises';
import { join } from 'path';
import { loadConfig, configFilePath } from '../core/config.js';
import { existsSync } from 'fs';

export function logCommand(): Command {
  const cmd = new Command('log');

  cmd
    .description('Display the Ratchet log for a target')
    .option('-t, --target <name>', 'Target name to show log for')
    .option('--raw', 'Print raw markdown without color formatting', false)
    .action(async (options: { target?: string; raw: boolean }) => {
      const cwd = process.cwd();

      console.log(chalk.bold('\n⚙  Ratchet Log\n'));

      let targetName = options.target;

      // Auto-detect target from config or docs directory
      if (!targetName) {
        targetName = await inferTarget(cwd);
        if (!targetName) {
          console.error(
            chalk.red('  No target specified and none could be inferred.') +
              '\n  Use ' +
              chalk.cyan('ratchet log --target <name>'),
          );
          process.exit(1);
        }
      }

      const logPath = join(cwd, 'docs', `${targetName}-ratchet.md`);

      let content: string;
      try {
        content = await readFile(logPath, 'utf-8');
      } catch {
        console.error(
          chalk.red(`  No log found for target "${targetName}".`) +
            `\n  Expected: ${chalk.dim(logPath)}`,
        );
        process.exit(1);
      }

      if (options.raw) {
        console.log(content);
        return;
      }

      renderMarkdown(content);
    });

  return cmd;
}

async function inferTarget(cwd: string): Promise<string | null> {
  // Try config first
  if (existsSync(configFilePath(cwd))) {
    try {
      const config = loadConfig(cwd);
      if (config.targets.length === 1) {
        return config.targets[0].name;
      }
      if (config.targets.length > 1) {
        const names = config.targets.map((t) => chalk.cyan(t.name)).join(', ');
        console.error(
          chalk.yellow('  Multiple targets in .ratchet.yml. Specify one with --target.') +
            `\n  Available: ${names}`,
        );
        process.exit(1);
      }
    } catch {
      // ignore
    }
  }

  // Fall back to docs directory
  const docsDir = join(cwd, 'docs');
  try {
    const files = await readdir(docsDir);
    const logFiles = files.filter((f) => f.endsWith('-ratchet.md'));
    if (logFiles.length === 1) {
      return logFiles[0].replace(/-ratchet\.md$/, '');
    }
    if (logFiles.length > 1) {
      const names = logFiles
        .map((f) => chalk.cyan(f.replace(/-ratchet\.md$/, '')))
        .join(', ');
      console.error(
        chalk.yellow('  Multiple log files found. Specify one with --target.') +
          `\n  Available: ${names}`,
      );
      process.exit(1);
    }
  } catch {
    // docs dir doesn't exist
  }

  return null;
}

function renderMarkdown(content: string): void {
  const lines = content.split('\n');

  for (const line of lines) {
    if (line.startsWith('# ')) {
      console.log(chalk.bold.white(line));
    } else if (line.startsWith('## ')) {
      // Colorize click status indicators
      if (line.includes('✅')) {
        console.log('\n' + chalk.bold.green(line));
      } else if (line.includes('❌')) {
        console.log('\n' + chalk.bold.red(line));
      } else {
        console.log('\n' + chalk.bold.cyan(line));
      }
    } else if (line.startsWith('### ')) {
      console.log(chalk.bold(line));
    } else if (line.startsWith('> ')) {
      console.log(chalk.italic.dim(line));
    } else if (line.startsWith('| ')) {
      console.log(chalk.dim(line));
    } else if (line === '---') {
      console.log(chalk.dim('─'.repeat(60)));
    } else if (line.startsWith('*Generated by')) {
      console.log(chalk.dim(line));
    } else {
      console.log(line);
    }
  }
}
