import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import type { RatchetRun, Click } from '../types.js';

/**
 * RatchetLogger — writes a living markdown log to docs/<target>-ratchet.md.
 * Each click is appended as it completes; the file is finalized at run end.
 */
export class RatchetLogger {
  private logPath: string;

  constructor(targetName: string, cwd: string = process.cwd()) {
    this.logPath = join(cwd, 'docs', `${targetName}-ratchet.md`);
  }

  /** Initialize the log file with a header. Call once at run start. */
  async initLog(run: RatchetRun): Promise<void> {
    await mkdir(dirname(this.logPath), { recursive: true });
    await writeFile(this.logPath, this.buildHeader(run), 'utf-8');
  }

  /** Append a completed click to the log. */
  async logClick(run: RatchetRun, click: Click): Promise<void> {
    await mkdir(dirname(this.logPath), { recursive: true });

    let existing = '';
    try {
      existing = await readFile(this.logPath, 'utf-8');
    } catch {
      existing = this.buildHeader(run);
    }

    // Strip footer if present, then append click section
    const withoutFooter = this.stripFooter(existing);
    await writeFile(this.logPath, withoutFooter + '\n' + this.buildClickSection(click), 'utf-8');
  }

  /** Finalize the log with a summary footer. Call once at run end. */
  async finalizeLog(run: RatchetRun): Promise<void> {
    let existing = '';
    try {
      existing = await readFile(this.logPath, 'utf-8');
    } catch {
      existing = this.buildHeader(run);
    }

    const passedClicks = run.clicks.filter((c) => c.testsPassed).length;
    const totalClicks = run.clicks.length;
    const durationMs = run.finishedAt
      ? run.finishedAt.getTime() - run.startedAt.getTime()
      : 0;
    const duration = formatDuration(durationMs);

    const footer =
      `\n---\n` +
      `*Generated by [Ratchet](https://github.com/ratchet-run/ratchet) · ` +
      `${new Date().toISOString()} · ` +
      `${passedClicks}/${totalClicks} clicks landed · ` +
      `${duration}*\n`;

    await mkdir(dirname(this.logPath), { recursive: true });
    await writeFile(this.logPath, this.stripFooter(existing) + footer, 'utf-8');
  }

  /** Return the path to this log file. */
  get path(): string {
    return this.logPath;
  }

  private buildHeader(run: RatchetRun): string {
    return (
      `# Ratchet Log: \`${run.target.name}\`\n\n` +
      `> ${run.target.description}\n\n` +
      `| Field | Value |\n` +
      `|-------|-------|\n` +
      `| **Run ID** | \`${run.id}\` |\n` +
      `| **Target Path** | \`${run.target.path}\` |\n` +
      `| **Started** | ${run.startedAt.toISOString()} |\n` +
      `| **Status** | ${run.status} |\n\n` +
      `---\n`
    );
  }

  private buildClickSection(click: Click): string {
    const icon = click.testsPassed ? '✅' : '❌';
    const commitLine = click.commitHash
      ? `\`${click.commitHash.slice(0, 7)}\``
      : '*rolled back (pawl engaged)*';
    const filesList =
      click.filesModified.length > 0
        ? click.filesModified.map((f) => `\`${f}\``).join(', ')
        : '*none*';

    return (
      `## Click ${click.number} ${icon}\n\n` +
      `**${click.timestamp.toISOString()}** · commit: ${commitLine} · files: ${filesList}\n\n` +
      `### Analysis\n\n${click.analysis || '*none*'}\n\n` +
      `### Proposal\n\n${click.proposal || '*none*'}\n\n` +
      `---\n`
    );
  }

  private stripFooter(content: string): string {
    const marker = '\n---\n*Generated by [Ratchet]';
    const idx = content.lastIndexOf(marker);
    return idx === -1 ? content : content.slice(0, idx);
  }
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  const mins = Math.floor(ms / 60_000);
  const secs = Math.floor((ms % 60_000) / 1000);
  return `${mins}m ${secs}s`;
}
