import { execFile } from 'child_process';
import { promisify } from 'util';
import { logger } from '../lib/logger.js';
import { selectModel } from '../lib/model-router.js';

const execFileAsync = promisify(execFile);
const log = logger;

// ─── Types
export interface AgentProposal {
  agentName: string;
  personality: string;
  specialization: string;
  filesChanged: string[];
  scoreDelta: number;
  /** Summary generated by the agent describing what it changed and why */
  summary: string;
  diffStats: { additions: number; deletions: number };
}

export interface DebateArgument {
  fromAgent: string;
  /** Name of the agent whose proposal is being critiqued */
  aboutProposal: string;
  argument: string;
  stance: 'support' | 'oppose' | 'neutral';
}

export interface DebateVerdict {
  winner: string;
  reasoning: string;
  /** Agent names that disagreed with the verdict */
  dissent: string[];
  /** 0–1 confidence. If < 0.6, caller should fall back to score-based picking */
  confidence: number;
}

export interface DebateRound {
  proposals: AgentProposal[];
  arguments: DebateArgument[];
  verdict: DebateVerdict;
}

export interface DebateConfig {
  model?: string;
  /** Command to run judge (defaults to claude) */
  command?: string;
  /** Extra args for judge command */
  extraArgs?: string[];
  /** Timeout in ms for the judge call */
  timeoutMs?: number;
  /** Strategy context injected into judge prompt */
  strategyContext?: string;
}

// ─── Core Functions
/**
 * Skip debate if there is only 1 proposal or all proposals have the same scoreDelta.
 */
export function shouldDebate(proposals: AgentProposal[]): boolean {
  if (proposals.length <= 1) return false;

  const deltas = proposals.map((p) => p.scoreDelta);
  const allSame = deltas.every((d) => d === deltas[0]);
  if (allSame) return false;

  return true;
}

/**
 * Build the judge prompt with all proposals and optional strategy context.
 */
export function buildJudgePrompt(
  proposals: AgentProposal[],
  strategyContext?: string,
): string {
  const lines: string[] = [];

  lines.push('You are a CODE REVIEW JUDGE evaluating competing agent proposals in a swarm code improvement system.');
  lines.push('Each agent made independent changes to the same codebase. Your job: pick the best one.');
  lines.push('');

  if (strategyContext) {
    lines.push('## Project Context');
    lines.push(strategyContext);
    lines.push('');
  }

  lines.push('## Proposals');
  lines.push('');

  for (const p of proposals) {
    lines.push(`### Agent: ${p.agentName}`);
    lines.push(`- **Personality:** ${p.personality}`);
    lines.push(`- **Specialization:** ${p.specialization}`);
    lines.push(`- **Score delta:** ${p.scoreDelta > 0 ? '+' : ''}${p.scoreDelta}`);
    lines.push(`- **Files changed:** ${p.filesChanged.length > 0 ? p.filesChanged.join(', ') : 'none'}`);
    lines.push(`- **Diff stats:** +${p.diffStats.additions} / -${p.diffStats.deletions}`);
    lines.push(`- **Summary:** ${p.summary}`);
    lines.push('');
  }

  lines.push('## Evaluation Criteria');
  lines.push('Consider in order:');
  lines.push('1. **Safety** — does the change introduce risk? (lower diff stats = lower risk)');
  lines.push('2. **Impact** — does the change genuinely improve the codebase? (score delta is one signal)');
  lines.push('3. **Precision** — is the change targeted and purposeful?');
  lines.push('4. **Completeness** — does it fix the root cause or just the symptom?');
  lines.push('');
  lines.push('## Instructions');
  lines.push('');
  lines.push('Respond in this EXACT JSON format (no markdown, no extra text):');
  lines.push('');
  lines.push('{');
  lines.push('  "winner": "<agentName>",');
  lines.push('  "reasoning": "<1-2 sentences explaining why this proposal wins>",');
  lines.push('  "dissent": ["<agentName>", ...],');
  lines.push('  "confidence": <0.0-1.0>');
  lines.push('}');
  lines.push('');
  lines.push('- winner: must exactly match one of the agent names listed above');
  lines.push('- dissent: agents whose proposals were competitive but lost (can be empty [])');
  lines.push('- confidence: 1.0 = clear winner, 0.5 = toss-up, < 0.6 = fall back to score-based');

  return lines.join('\n');
}

/**
 * Parse the judge's JSON response into a DebateVerdict.
 * Tolerant: if parsing fails, returns a low-confidence result.
 */
export function parseVerdict(response: string, proposals: AgentProposal[]): DebateVerdict {
  // Extract JSON block — handle cases where the model wraps in markdown
  const jsonMatch = response.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    log.warn({ response }, 'debate: could not extract JSON from judge response');
    return buildFallbackVerdict(proposals);
  }

  try {
    const parsed = JSON.parse(jsonMatch[0]) as {
      winner?: string;
      reasoning?: string;
      dissent?: string[];
      confidence?: number;
    };

    const winner = parsed.winner ?? '';
    const agentNames = proposals.map((p) => p.agentName);

    // Validate winner exists
    if (!agentNames.includes(winner)) {
      log.warn({ winner, agentNames }, 'debate: judge picked unknown agent, falling back');
      return buildFallbackVerdict(proposals);
    }

    return {
      winner,
      reasoning: parsed.reasoning ?? 'No reasoning provided.',
      dissent: (parsed.dissent ?? []).filter((n) => agentNames.includes(n)),
      confidence: clamp(parsed.confidence ?? 0.5, 0, 1),
    };
  } catch (err) {
    log.warn({ err }, 'debate: failed to parse judge JSON');
    return buildFallbackVerdict(proposals);
  }
}

function buildFallbackVerdict(proposals: AgentProposal[]): DebateVerdict {
  // Fallback: pick by score delta
  const sorted = [...proposals].sort((a, b) => b.scoreDelta - a.scoreDelta);
  const winner = sorted[0];
  return {
    winner: winner?.agentName ?? '',
    reasoning: 'Judge response could not be parsed. Fell back to highest score delta.',
    dissent: [],
    confidence: 0.4, // below threshold — will trigger score-based fallback
  };
}

function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n));
}

/**
 * Run the full debate: call judge, parse verdict, return DebateRound.
 */
export async function runDebate(
  proposals: AgentProposal[],
  config: DebateConfig = {},
): Promise<DebateRound> {
  const command = config.command ?? 'claude';
  const baseArgs = config.extraArgs ?? ['--print', '--permission-mode', 'bypassPermissions'];

  // Debate judging is a complex reasoning task — default to the premium model tier
  const judgeModel = config.model ?? selectModel('complex');
  if (!baseArgs.some((a) => a.startsWith('--model'))) {
    baseArgs.push('--model', judgeModel);
  }

  const judgePrompt = buildJudgePrompt(proposals, config.strategyContext);

  log.info(
    { agentCount: proposals.length, agents: proposals.map((p) => p.agentName) },
    'debate: starting judge evaluation',
  );

  let judgeResponse = '';
  let verdict: DebateVerdict;

  try {
    const { stdout } = await execFileAsync(command, [...baseArgs, judgePrompt], {
      timeout: config.timeoutMs ?? 60_000,
      maxBuffer: 10 * 1024 * 1024,
    });
    judgeResponse = stdout.trim();
    verdict = parseVerdict(judgeResponse, proposals);
  } catch (err) {
    log.warn({ err }, 'debate: judge call failed, using fallback verdict');
    verdict = buildFallbackVerdict(proposals);
  }

  // Build debate arguments from each personality's debateStyle
  // (In a real implementation these would come from agent calls;
  //  here we synthesize them from the personality's known debate style)
  const arguments_: DebateArgument[] = [];
  for (const proposal of proposals) {
    const otherProposals = proposals.filter((p) => p.agentName !== proposal.agentName);
    for (const other of otherProposals) {
      // Winning proposal gets "neutral" stances from others; losing proposals get "oppose"
      const stance: 'support' | 'oppose' | 'neutral' =
        proposal.agentName === verdict.winner ? 'support' : 'neutral';
      arguments_.push({
        fromAgent: proposal.agentName,
        aboutProposal: other.agentName,
        argument: `[${proposal.personality}] evaluating proposal from ${other.personality}`,
        stance,
      });
    }
  }

  log.info(
    {
      winner: verdict.winner,
      confidence: verdict.confidence,
      reasoning: verdict.reasoning,
    },
    'debate: verdict reached',
  );

  return {
    proposals,
    arguments: arguments_,
    verdict,
  };
}
