import { describe, it, expect } from 'vitest';
import {
  loadStrategy,
  saveStrategy,
  initStrategy,
  evolveStrategy,
  buildStrategyContext,
  getRecommendation,
  dominantExtension,
  detectTechStack,
  detectTestFramework,
  detectPatterns,
  estimateTotalFiles,
  isSimilarDescription,
} from './core/strategy.js';
import { ScanResult } from './core/scanner.js';
import { Strategy, CodebaseProfile, StrategyInsight, HotSpot, AntiPattern, RunSummary } from './types.js';

// Mock file system for strategy tests
const mockFs = {
  existsSync: (path: string) => path === '.ratchet/strategy.md',
  readFileSync: (path: string) => `---
version: 1
createdAt: 2024-01-01T00:00:00.000Z
updatedAt: 2024-01-01T00:00:00.000Z
profile.name: TestProject
profile.techStack: ["Node.js", "TypeScript"]
profile.patterns: ["src/ layout", "dedicated test directory"]
profile.testFramework: vitest
profile.totalFiles: 150
profile.lastScanned: 2024-01-01T00:00:00.000Z
insights: []
hotSpots: []
antiPatterns: []
runSummaries: []
---
# Ratchet Strategy — TestProject

> Auto-generated by Ratchet v1. Last updated: 2024-01-01
`,
  mkdir: (path: string) => {},
  writeFile: (path: string, content: string) => {},
};

// Helper to create mock scan result
function createMockScanResult(total: number, categories: any[] = []): ScanResult {
  return {
    total,
    categories,
    totalIssuesFound: total,
    maxScore: 100,
    files: [],
    issues: [],
    issuesByFile: new Map(),
    issuesBySubcategory: new Map(),
    issuesByCategory: new Map(),
    timestamp: new Date(),
    target: { name: 'test', path: '.' },
    projectName: 'test-project',
  };
}

// Helper to create mock ratchet run
function createMockRun(clicks: any[] = []): any {
  return {
    id: 'test-run',
    target: { name: 'test', path: '.' },
    clicks,
    startedAt: new Date(),
    finishedAt: new Date(),
    status: 'completed',
    resumeState: undefined,
    falsePositivesFound: 0,
    skippedClicks: 0,
    earlyStopReason: undefined,
    timeoutReached: false,
    budgetReached: false,
    architectEscalated: false,
    sweepEscalated: false,
    reactAnalysis: undefined,
    planResult: undefined,
  };
}

// Mock Click interface for testing
interface MockClick {
  number: number;
  testsPassed: boolean;
  rolledBack: boolean;
  commitHash?: string;
  scoreAfterClick?: number;
  filesModified: string[];
  proposal?: string;
  rollbackReason?: string;
  locDelta?: number;
  swarmSpecialization?: string;
}

describe('Strategy Module', () => {
  describe('File I/O', () => {
    it('should load strategy from file correctly', async () => {
      const originalExistsSync = existsSync;
      const originalReadFileSync = readFileSync;
      
      // Override for testing
      (existsSync as any) = (path: string) => mockFs.existsSync(path);
      (readFileSync as any) = (path: string) => mockFs.readFileSync(path);

      const strategy = await loadStrategy('/tmp');
      
      expect(strategy).not.toBeNull();
      expect(strategy?.version).toBe(1);
      expect(strategy?.profile.name).toBe('TestProject');
      expect(strategy?.profile.techStack).toEqual(['Node.js', 'TypeScript']);
      expect(strategy?.insights).toEqual([]);
      expect(strategy?.hotSpots).toEqual([]);
      expect(strategy?.antiPatterns).toEqual([]);
      expect(strategy?.runSummaries).toEqual([]);

      // Restore original functions
      (existsSync as any) = originalExistsSync;
      (readFileSync as any) = originalReadFileSync;
    });

    it('should handle missing strategy file gracefully', async () => {
      const originalExistsSync = existsSync;
      
      // Override for testing
      (existsSync as any) = (path: string) => false;

      const strategy = await loadStrategy('/tmp');
      
      expect(strategy).toBeNull();

      // Restore original function
      (existsSync as any) = originalExistsSync;
    });

    it('should initialize strategy from scan result', () => {
      const scan = createMockScanResult(150);
      const strategy = initStrategy('/tmp', scan);

      expect(strategy).not.toBeNull();
      expect(strategy.version).toBe(1);
      expect(strategy.profile.name).toBe('test-project');
      expect(strategy.profile.techStack).toContain('TypeScript');
      expect(strategy.profile.totalFiles).toBe(150);
      expect(strategy.insights).toEqual([]);
      expect(strategy.hotSpots).toEqual([]);
      expect(strategy.antiPatterns).toEqual([]);
      expect(strategy.runSummaries).toEqual([]);
    });

    it('should save strategy to file', async () => {
      const originalExistsSync = existsSync;
      const originalMkdir = mkdir;
      const originalWriteFile = writeFile;

      const mkdirCalls: string[] = [];
      const writeFileCalls: { path: string; content: string }[] = [];

      (existsSync as any) = (path: string) => true;
      (mkdir as any) = (path: string) => { mkdirCalls.push(path); };
      (writeFile as any) = (path: string, content: string) => { writeFileCalls.push({ path, content }); };

      const strategy: any = {
        version: 2,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-02T00:00:00.000Z',
        profile: {
          name: 'TestProject',
          techStack: ['Node.js', 'TypeScript'],
          patterns: ['src/ layout'],
          testFramework: 'vitest',
          totalFiles: 150,
          lastScanned: '2024-01-02T00:00:00.000Z',
        },
        insights: [],
        hotSpots: [],
        antiPatterns: [],
        runSummaries: [],
      };

      await saveStrategy('/tmp', strategy);

      expect(mkdirCalls).toContain('.ratchet');
      expect(writeFileCalls).toHaveLength(1);
      expect(writeFileCalls[0].path).toBe('/tmp/.ratchet/strategy.md');
      
      // Verify content has expected fields
      expect(writeFileCalls[0].content).toContain('version: 2');
      expect(writeFileCalls[0].content).toContain('TestProject');
      expect(writeFileCalls[0].content).toContain('Node.js');

      // Restore original functions
      (existsSync as any) = originalExistsSync;
      (mkdir as any) = originalMkdir;
      (writeFile as any) = originalWriteFile;
    });
  });

  describe('Strategy Evolution', () => {
    it('should evolve strategy after a run with positive outcome', async () => {
      // Create a successful run
      const scanBefore = createMockScanResult(100);
      const scanAfter = createMockScanResult(120);
      
      const landedClick: MockClick = {
        number: 1,
        testsPassed: true,
        rolledBack: false,
        commitHash: 'abc123',
        scoreAfterClick: 120,
        filesModified: ['src/file1.ts', 'src/file2.ts'],
        locDelta: -50,
      };

      const run = createMockRun([landedClick]);

      const originalLoadStrategy = loadStrategy;
      const originalSaveStrategy = saveStrategy;

      // Mock loadStrategy to return empty strategy initially
      (loadStrategy as any) = async () => {
        return {
          version: 1,
          createdAt: '2024-01-01T00:00:00.000Z',
          updatedAt: '2024-01-01T00:00:00.000Z',
          profile: {
            name: 'test-project',
            techStack: ['TypeScript'],
            patterns: [],
            testFramework: 'vitest',
            totalFiles: 150,
            lastScanned: '2024-01-01T00:00:00.000Z',
          },
          insights: [],
          hotSpots: [],
          antiPatterns: [],
          runSummaries: [],
        };
      };

      // Mock saveStrategy to capture calls
      let saveCalled = false;
      (saveStrategy as any) = async (cwd: string, strategy: any) => {
        saveCalled = true;
        expect(strategy.version).toBe(2);
        expect(strategy.updatedAt).not.toBe('2024-01-01T00:00:00.000Z');
        expect(strategy.runSummaries).toHaveLength(1);
        expect(strategy.runSummaries[0].scoreBefore).toBe(100);
        expect(strategy.runSummaries[0].scoreAfter).toBe(120);
        expect(strategy.runSummaries[0].landed).toBe(1);
        expect(strategy.runSummaries[0].rolledBack).toBe(0);
        expect(strategy.runSummaries[0].keyInsight).toContain('Strong run');
      };

      const result = await evolveStrategy('/tmp', run, scanBefore, scanAfter);

      expect(result.updated.version).toBe(2);
      expect(result.keyInsight).toContain('Strong run');

      // Verify save was called
      expect(saveCalled).toBe(true);

      // Restore original functions
      (loadStrategy as any) = originalLoadStrategy;
      (saveStrategy as any) = originalSaveStrategy;
    });

    it('should handle run with all clicks rolled back', async () => {
      const scanBefore = createMockScanResult(100);
      const scanAfter = createMockScanResult(100);

      const rolledBackClick: MockClick = {
        number: 1,
        testsPassed: false,
        rolledBack: true,
        rollbackReason: 'test failures',
        filesModified: ['src/file1.ts'],
      };

      const run = createMockRun([rolledBackClick]);

      const originalLoadStrategy = loadStrategy;
      const originalSaveStrategy = saveStrategy;

      // Mock loadStrategy
      (loadStrategy as any) = async () => ({
        version: 1,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z',
        profile: { name: 'test-project', techStack: ['TypeScript'], patterns: [], testFramework: 'vitest', totalFiles: 150, lastScanned: '2024-01-01T00:00:00.000Z' },
        insights: [],
        hotSpots: [],
        antiPatterns: [],
        runSummaries: [],
      });

      let saveCalled = false;
      (saveStrategy as any) = async (cwd: string, strategy: any) => {
        saveCalled = true;
        expect(strategy.runSummaries).toHaveLength(1);
        expect(strategy.runSummaries[0].keyInsight).toContain('All clicks rolled back');
      };

      const result = await evolveStrategy('/tmp', run, scanBefore, scanAfter);

      expect(result.keyInsight).toContain('All clicks rolled back');
      expect(saveCalled).toBe(true);

      // Restore
      (loadStrategy as any) = originalLoadStrategy;
      (saveStrategy as any) = originalSaveStrategy;
    });
  });

  describe('Strategy Context Builder', () => {
    it('should build concise strategy context for agent prompts', () => {
      const strategy: any = {
        version: 2,
        profile: { name: 'TestProject' },
        insights: [
          { type: 'what-works', description: 'Changes to .ts files land cleanly', confidence: 0.8, evidence: '10/10 landed', runId: 'run1', createdAt: '2024-01-01' },
          { type: 'what-fails', description: 'Multi-file changes cause rollbacks', confidence: 0.7, evidence: '5/5 rolled back', runId: 'run2', createdAt: '2024-01-02' },
        ],
        hotSpots: [
          { filePath: 'src/hard-file.ts', rollbackRate: 0.8, attempts: 5, lastAttempt: '2024-01-03', notes: 'Very complex' },
        ],
        antiPatterns: [
          { pattern: 'Touching too many files', occurrences: 3, lastSeen: '2024-01-03', example: 'Click 1 rolled back' },
        ],
        runSummaries: [
          { runId: 'run3', date: '2024-01-03', mode: 'normal', scoreBefore: 100, scoreAfter: 120, landed: 3, rolledBack: 0, keyInsight: 'Strong run' },
        ],
      };

      const context = buildStrategyContext(strategy);
      
      expect(context).toContain('STRATEGY CONTEXT');
      expect(context).toContain('✅ Changes to .ts files land cleanly');
      expect(context).toContain('⚠️  src/hard-file.ts');
      expect(context).toContain('❌ Touching too many files');
      expect(context).toContain('Last run: +20 score');
    });

    it('should return empty string when no useful context available', () => {
      const strategy: any = {
        version: 1,
        profile: { name: 'TestProject' },
        insights: [],
        hotSpots: [],
        antiPatterns: [],
        runSummaries: [],
      };

      const context = buildStrategyContext(strategy);
      expect(context).toBe('');
    });
  });

  describe('Recommendation Engine', () => {
    it('should provide recommendations based on strategy', () => {
      const strategy: any = {
        version: 2,
        hotSpots: [
          { filePath: 'src/complex-module.ts', rollbackRate: 0.85, attempts: 4, lastAttempt: '2024-01-03', notes: 'High complexity' },
        ],
        insights: [
          { type: 'what-works', description: 'Small focused changes land well', confidence: 0.7, evidence: '8/8 landed', runId: 'run1', createdAt: '2024-01-01' },
          { type: 'what-fails', description: 'Changes to config files cause issues', confidence: 0.6, evidence: '3/4 rolled back', runId: 'run2', createdAt: '2024-01-02' },
        ],
        antiPatterns: [
          { pattern: 'Modifying multiple config files', occurrences: 2, lastSeen: '2024-01-02', example: 'Click 2 rolled back' },
        ],
      };

      const recommendation = getRecommendation(strategy, 'src/complex-module.ts');
      
      expect(recommendation).toContain('⚠️  This file has a 85% rollback rate');
      expect(recommendation).toContain('Recommended approaches:');
      expect(recommendation).toContain('Small focused changes land well');
    });

    it('should handle unknown files gracefully', () => {
      const strategy: any = {
        version: 1,
        hotSpots: [],
        insights: [],
        antiPatterns: [],
      };

      const recommendation = getRecommendation(strategy, 'src/unknown-file.ts');
      expect(recommendation).toBe('No recommendation available yet.');
    });
  });

  describe('Utility Functions', () => {
    it('should detect dominant file extension', () => {
      const files1 = ['src/file1.ts', 'src/file2.ts', 'src/file3.ts'];
      expect(dominantExtension(files1)).toBe('.ts');

      const files2 = ['src/file1.ts', 'src/file2.ts', 'src/file3.js'];
      expect(dominantExtension(files2)).toBe('.ts'); // .ts has 2, .js has 1

      const files3 = ['src/file1.js', 'src/file2.js', 'src/file3.js'];
      expect(dominantExtension(files3)).toBe('.js');

      const files4 = ['src/file1.py', 'src/file2.ts', 'src/file3.js'];
      expect(dominantExtension(files4)).toBe('.py'); // .py has 1 but others have 1 each, first with max count

      const files5 = ['src/file1', 'src/file2'];
      expect(dominantExtension(files5)).toBe(null);
    });

    it('should detect tech stack from project files', () => {
      // Mock file system
      const originalExistsSync = existsSync;
      const cwd = '/tmp';

      // Test Node.js detection
      (existsSync as any) = (path: string) => {
        const files = ['package.json', 'tsconfig.json', 'vitest.config.ts'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['Node.js', 'TypeScript', 'vitest']);

      // Test Python detection
      (existsSync as any) = (path: string) => {
        const files = ['pyproject.toml', 'pytest.ini'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['Python', 'pytest']);

      // Test Rust detection
      (existsSync as any) = (path: string) => {
        const files = ['Cargo.toml'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['Rust']);

      // Test Go detection
      (existsSync as any) = (path: string) => {
        const files = ['go.mod'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['Go']);

      // Test Java detection
      (existsSync as any) = (path: string) => {
        const files = ['pom.xml', 'build.gradle'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['Java/Maven', 'Java/Gradle']);

      // Test Ruby detection
      (existsSync as any) = (path: string) => {
        const files = ['Gemfile'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['Ruby']);

      // Test PHP detection
      (existsSync as any) = (path: string) => {
        const files = ['composer.json'];
        return files.includes(path);
      };
      expect(detectTechStack(cwd)).toEqual(['PHP']);

      // Restore
      (existsSync as any) = originalExistsSync;
    });

    it('should detect test framework correctly', () => {
      const originalExistsSync = existsSync;
      const originalReadFileSync = readFileSync;
      const cwd = '/tmp';

      // Test vitest detection
      (existsSync as any) = (path: string) => {
        const files = ['vitest.config.ts', 'package.json'];
        return files.includes(path);
      };
      (readFileSync as any) = (path: string) => {
        if (path.includes('package.json')) {
          return JSON.stringify({ devDependencies: { vitest: '^1.0.0' } });
        }
        return '';
      };
      expect(detectTestFramework(cwd)).toBe('vitest');

      // Test jest detection
      (existsSync as any) = (path: string) => {
        const files = ['jest.config.ts', 'package.json'];
        return files.includes(path);
      };
      (readFileSync as any) = (path: string) => {
        if (path.includes('package.json')) {
          return JSON.stringify({ devDependencies: { jest: '^30.0.0' } });
        }
        return '';
      };
      expect(detectTestFramework(cwd)).toBe('jest');

      // Test pytest detection
      (existsSync as any) = (path: string) => {
        const files = ['pytest.ini', 'pyproject.toml'];
        return files.includes(path);
      };
      expect(detectTestFramework(cwd)).toBe('pytest');

      // Test unknown detection
      (existsSync as any) = (path: string) => false;
      expect(detectTestFramework(cwd)).toBe('unknown');

      // Restore
      (existsSync as any) = originalExistsSync;
      (readFileSync as any) = originalReadFileSync;
    });

    it('should detect codebase patterns', () => {
      const originalExistsSync = existsSync;
      const cwd = '/tmp';

      // Test various patterns
      (existsSync as any) = (path: string) => {
        const patterns = {
          'src': true,
          'tests': true,
          '.ratchet': true,
        };
        return patterns[path as keyof typeof patterns] ?? false;
      };
      expect(detectPatterns(cwd, createMockScanResult(0))).toEqual([
        'src/ layout',
        'dedicated test directory',
        'ratchet-enabled',
      ]);

      // Test inference from scan categories
      const scanWithCategories = createMockScanResult(0, [
        { name: 'Type Safety', score: 80, max: 100, subcategories: [] },
        { name: 'Testing', score: 90, max: 100, subcategories: [] },
      ]);
      expect(detectPatterns(cwd, scanWithCategories)).toEqual([
        'src/ layout',
        'dedicated test directory',
        'ratchet-enabled',
        'typed',
        'tested',
      ]);

      // Restore
      (existsSync as any) = originalExistsSync;
    });

    it('should estimate total files from scan', () => {
      const scanWithIssues = createMockScanResult(100);
      expect(estimateTotalFiles(scanWithIssues)).toBe(200); // 100 * 2

      const scanWithZeroIssues = createMockScanResult(0);
      expect(estimateTotalFiles(scanWithZeroIssues)).toBe(0);

      const scanWithNegative = createMockScanResult(-10);
      expect(estimateTotalFiles(scanWithNegative)).toBe(0); // Should handle negative gracefully
    });

    it('should check description similarity', () => {
      expect(isSimilarDescription('Changes to .ts files land cleanly', 'Changes to .ts files have high success rate')).toBe(true);
      expect(isSimilarDescription('Multi-file changes cause rollbacks', 'Single-file changes are safe')).toBe(false);
      expect(isSimilarDescription('What works: .ts files', 'What works: .js files')).toBe(false);
    });
  });
});